import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
    marginHorizontal: "4%",
    marginTop: 45,
  },
  container1: {
    flex: 1,
    backgroundColor: "#F9C877",
    marginHorizontal: "4%",
    marginTop: 15,
    borderRadius: 8,
  },
  floatingButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#76CE9E",
    borderRadius: 30,
    width: 60,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
  },
  modalView: {
    margin: 16,
    marginTop: 215,
    paddingBottom: 20,
    backgroundColor: "white",
    borderRadius: 20,
    paddingTop: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  input: {
    height: 40,
    borderColor: "gray",
    color: "#f0f5f5",
    fontSize: 12,
    borderWidth: 1,
    borderRadius: 12,
    marginVertical: 5,
    padding: 5,
    width: 250,
  },
  addButton: {
    backgroundColor: "#76CE9E",
    padding: 10,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
    height: 40,
    width: 250,
  },
  name: {
    fontSize: 19,
    fontWeight: "bold",
    color: "#fff",
    marginLeft: 20,
    paddingTop: 6,
  },
  name2: {
    fontSize: 12,
    color: "#fff",
    marginLeft: 20,
  },
});
